from ETL.Settings.auth import *
from ETL.Settings.base import * 
from ETL.Settings.database import *
from ETL.Settings.middleware import *
from ETL.Settings.static import *
from ETL.Settings.templates import *


ALLOWED_HOSTS,
AUTH_PASSWORD_VALIDATORS,
AUTH_USER_MODEL,
AUTHENTICATION_BACKENDS,
ACCOUNT_EMAIL_REQUIRED,
ACCOUNT_USERNAME_REQUIRED,
ACCOUNT_AUTHENTICATION_METHOD,
ACCOUNT_USERNAME_REQUIRED,
ACCOUNT_USER_MODEL_USERNAME_FIELD,
ACCOUNT_EMAIL_REQUIRED,
ACCOUNT_EMAIL_VERIFICATION,
ACCOUNT_UNIQUE_EMAIL,
ACCOUNT_CONFIRM_EMAIL_ON_GET,
ACCOUNT_ADAPTER,

BASE_DIR,
CORS_ALLOWED_ORIGINS,
CORS_ALLOW_ALL_ORIGINS,
DEBUG,
DEFAULT_AUTO_FIELD,
DJANGO_ENV,
DEFAULT_FILE_STORAGE,
REST_FRAMEWORK,
ROOT_URLCONF,
REST_USE_JWT,
SECRET_KEY,
WSGI_APPLICATION,
WAGTAIL_SITE_NAME,

INSTALLED_APPS,
LANGUAGE_CODE ,
TIME_ZONE,
USE_I18N,
USE_TZ,

DATABASES,
MIDDLEWARE,
STATIC_URL,
SITE_ID,
SIMPLE_JWT,
MEDIA_ROOT,
MEDIA_URL,
MEDIA_URL_2,
TEMPLATES,